framework:
    messenger:
        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                    - validation
                    - doctrine_transaction

            query.bus:
                middleware:
                    - validation

        transports:
            async: "%env(MESSENGER_TRANSPORT_DSN)%"
            sync: 'sync://'

        routing:
            Domain\Shared\Bus\Command\Command: sync
            Domain\Shared\Bus\Query\Query: sync